#standard keys for db connection in springboot
spring: 
  datasource:
    password: root123
    url: jdbc:mysql://pwskills_octbatch
    username: root  
---
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
 ---
spring:
  config:
    activate:
      on-profile: 
      -qa
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource    
---
spring:
  config:
    activate:
      on-profile:
      - uat
  datasource:
    username: system
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: system123
    type: oracle:ucp.jdbc.PoolDataSource       
---
spring:
  config:
    activate:
      on-profile:
      -prod
  datasource:
    username: system
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: system123
    