#standard keys for db connection in springboot
# Common DB configuration
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/pwskills_octbatch

---
# DEV
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource

---
# QA
spring:
  config:
    activate:
      on-profile:
        - qa
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource

---
# UAT
spring:
  config:
    activate:
      on-profile:
        - uat
  datasource:
    username: system
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: system123
    type: oracle.ucp.jdbc.PoolDataSource

---
# PROD
spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    username: system
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: system123

---
# PRODST
spring:
  config:
    activate:
      on-profile:
        - prodst
  datasource:
    username: system
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: system123