#standard keys for db connection in springboot
spring: 
  datasource:
    password: root123
    url: jdbc:mysql://pwskills_octbatch
    username: root
    
---
spring:
  profiles:
    active:
    - dev
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
     
---
spring:
  profiles:
    active:
    - qa
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
      
---
spring:
  profiles:
    active:
    - uat
  datasource:
    username: system
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: system123
    type: oracle:ucp.jdbc.PoolDataSource
         
---
spring:
  profiles:
    active:
    - prod
  datasource:
    username: system
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: system123
    